package application.domain.enums;

/**
 * Tipo de operación de negocio que se registra en la auditoría (MongoDB).
 */
public enum OperationType {

    USER_REGISTERED,
    SELLER_APPROVED,
    SELLER_SUSPENDED,
    USER_BLOCKED,
    USER_ACTIVATED,
    PRODUCT_CREATED,
    PRODUCT_PRICE_CHANGED,
    PRODUCT_STATUS_CHANGED,
    WAREHOUSE_CREATED,
    WAREHOUSE_STATUS_CHANGED,
    INVENTORY_CREATED,
    INVENTORY_MOVEMENT,
    ORDER_PLACED,
    ORDER_PAID,
    ORDER_CANCELLED,
    INVOICE_ISSUED,
    SHIPMENT_CREATED,
    SHIPMENT_DISPATCHED,
    SHIPMENT_DELIVERED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    RETURN_RECEIVED,
    REFUND_COMPLETED
}
