services:
  mysql:
    image: mysql:8.0
    container_name: nexusmarket-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nexusmarket
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:7.0
    container_name: nexusmarket-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
